apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-09-26T07:03:06Z"
  labels:
    app: profile
    pod-template-hash: 7cf4cd456
  name: profile-svc
  namespace: default
  resourceVersion: "930610"
  uid: 2515d4a6-c7e4-4f4d-9e97-423bb330d6e5
spec:
  clusterIP: 10.104.251.137
  clusterIPs:
  - 10.104.251.137
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30301
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: profile
    pod-template-hash: 7cf4cd456
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}