apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-10-24T10:22:46Z"
  labels:
    app: profile
  name: profile-svc
  namespace: default
  resourceVersion: "3229396"
  uid: 29d39fd4-bb82-447b-95f5-f6ee6ce18b9a
spec:
  clusterIP: 10.105.252.208
  clusterIPs:
  - 10.105.252.208
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32607
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: profile
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}